// AudioPlayer.swift
// Generated by ChatGPT

import AVFoundation

class AudioPlayer: ObservableObject {
    static let shared = AudioPlayer()

    private var audioPlayer: AVAudioPlayer?

    init() {
        setupAudioPlayer()
    }

    private func setupAudioPlayer() {
        guard let url = Bundle.main.url(forResource: "Sounds/music", withExtension: "mp3") else {
            return
        }

        do {
            audioPlayer = try AVAudioPlayer(contentsOf: url)
            audioPlayer?.numberOfLoops = -1
            audioPlayer?.play()
        } catch {
            print("Error initializing audio player: \(error.localizedDescription)")
        }
    }
    
    func play(){
        audioPlayer?.play()
    }
}

