// SoundEffectPlayer.swift
// Generated by ChatGPT

import AVFoundation

class SoundEffectPlayer {
    static let shared = SoundEffectPlayer()

    private var audioPlayer: AVAudioPlayer?

    private init() {}

    func playCoinSound() {
        playSound(fileName: "coins", fileType: "mp3")
    }

    private func playSound(fileName: String, fileType: String) {
        guard let soundPath = Bundle.main.path(forResource: fileName, ofType: fileType) else {
            print("Sound file not found")
            return
        }

        do {
            audioPlayer = try AVAudioPlayer(contentsOf: URL(fileURLWithPath: soundPath))
            audioPlayer?.play()
        } catch {
            print("Error playing sound: \(error)")
        }
    }
}
